#3. Powershell Script that recurses contents of directory, finds C# files (excluding autogenerated ones)
# and outputs to a grid view where user can filter results etc.

# Script has been paramaterized so user can search any directory. User just calls function, presses tab
# and adds the directory they want to search. This way user doesn't alter script directly.



param(

    $path = "C:\HartPowerShellTask"
)


Get-ChildItem -Path $path -Exclude *aspx.designer.cs, *designer.cs -Filter *.cs   -Recurse|
Select-Object Name|Out-GridView







